---
driver:
  name: vagrant
  provision: true

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept

platforms:
  - name: debian-10
  - name: debian-11
    driver:
      vagrantfiles:
        - provision-debian11.rb
  - name: ubuntu-18.04
    driver:
      vagrantfiles:
        - provision-ubuntu.rb
  - name: centos-7.6
    driver:
      vagrantfiles:
        - provision-centos.rb
  - name: centos-8
    driver:
      vagrantfiles:
        - provision-centos8.rb
  - name: juniper/vqfx10k-re

suites:
  - name: exit1
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'exit1', ip: '192.168.0.1' }]
  - name: exit2
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'exit2', ip: '192.168.1.1' }]
  - name: exit3
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'exit3', ip: '192.168.2.1' }]
  - name: exit4
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'exit4', ip: '192.168.3.1' }]
  - name: spine1
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'exit1', ip: '192.168.0.2' }]
        - ['private_network', { virtualbox__intnet: 'exit2', ip: '192.168.1.2' }]
        - ['private_network', { virtualbox__intnet: 'exit3', ip: '192.168.2.2' }]
        - ['private_network', { virtualbox__intnet: 'exit4', ip: '192.168.3.2' }]
        - ['private_network', { virtualbox__intnet: 'leaf1', ip: '10.0.0.1' }]
  - name: leaf1
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'leaf1', ip: '10.0.0.2' }]
