require "/home/donatas/projects/frr-default-originate/provision.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/debian-9"
  c.vm.hostname = "spine1-debian-9.vagrantup.com"
  c.vm.network(:private_network, {:virtualbox__intnet=>"leaf1", :ip=>"10.0.0.1"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/donatas/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
